## Write a Numpy program to compute the multiplication of two given matrixes

In [3]:
import numpy as np

In [4]:
def matrixmul(m1,m2):
    m1 = np.array(m1)
    m2 = np.array(m2)
    result = np.matmul(m1,m2)
    print(result)


In [6]:
m1 = [[1,2],[2,1]]
m2 = [[1,2],[2,1]]
matrixmul(m1,m2)

[[5 4]
 [4 5]]


## Write a NumPy program to compute the determinant of a given square array

In [8]:
def matrixdet(m1):
    m1 = np.array(m1)
    result = np.linalg.det(m1)
    print(result)

In [9]:
m1 = [[1,2],[3,4]]
matrixdet(m1)

-2.0000000000000004


## Write a NumPy program to compute the cross product of two given vectors

In [11]:
def crossvec(v1,v2):
    result = np.cross(v1,v2)
    print(result)

In [14]:
v1 = [1,2,3]
v2 = [3,1,2]
crossvec(v1,v2)

[ 1  7 -5]


## Write a NumPy program to compute the condition number of a given matrix

In [18]:
def matrixcond(m1):
    m1 = np.array(m1)
    result = np.linalg.cond(m1)
    print(result)

In [19]:
m1 = [[ 1,  2, 3],
      [ 4,  5,  6],
      [ 7,  8,  9]]
matrixcond(m1)

5.0522794445385096e+16


## Write a NumPy program to compute the inverse of a given matrix

In [20]:
def matrixinv(m1):
    m1 = np.array(m1)
    result = np.linalg.inv(m1)
    print(result)

In [21]:
m1 = [[ 1,  2, 3],
      [ 4,  5,  6],
      [ 7,  8,  9]]
matrixinv(m1)

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
